Vagrant.configure("2") do |config| 
  config.vm.box = "bento/ubuntu-22.04-arm64"
  #config.vm.network "private_network", ip: "192.168.56.11"
  config.vm.provider "vmware_desktop" do |vmware|
    vmware.gui = false
    vmware.allowlist_verified = true
  end
end
