Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true

  config.vm.provision "file", source: "~/.ssh/authorized_keys", destination: "/tmp/authorized_keys"
  config.vm.provision "file", source: "~/.ssh/id_ed25519", destination: "/tmp/id_ed25519"

### debian ###
  config.vm.define "debian12" do |debian12|
    debian12.vm.box = "generic/debian12"
    debian12.vm.hostname = "debian12"
    debian12.vm.network "public_network", bridge: "enp2s0", ip: "192.168.1.100"
    debian12.vm.provider "virtualbox" do |vb|
      vb.cpus = 2
      vb.memory = "2048"
    end
    debian12.vm.provision "shell", path: "provision.sh"  
  end

### ubuntu ###
  config.vm.define "ubuntu22" do |ubuntu22|
    ubuntu22.vm.box = "ubuntu/jammy64"
    ubuntu22.vm.hostname = "ubuntu22"
    ubuntu22.vm.network "public_network", bridge: "enp2s0", ip: "192.168.1.101"
    ubuntu22.vm.provider "virtualbox" do |vb|
      vb.cpus = 2
      vb.memory = "2048"
    end
    ubuntu22.vm.provision "shell", path: "provision.sh"  
  end

#   config.vm.define "ubuntu20" do |ubuntu20|
#     ubuntu20.vm.box = "ubuntu/focal64"
#     ubuntu20.vm.hostname = "ubuntu20"
#     ubuntu20.vm.network "public_network", bridge: "enp2s0", ip: "192.168.1.102"
#     ubuntu20.vm.provider "virtualbox" do |vb|
#       vb.cpus = 2
#       vb.memory = "2048"
#     end
#     ubuntu20.vm.provision "shell", path: "provision.sh"  
#   end

# ### kali ###
#   config.vm.define "kali" do |kali|
#     kali.vm.box = "kalilinux/rolling"
#     kali.vm.hostname = "kali"
#     kali.vm.network "public_network", bridge: "enp2s0", ip: "192.168.1.103"
#     kali.vm.provider "virtualbox" do |vb|
#       vb.cpus = 2
#       vb.memory = "2048"
#     end
#     # kali.vm.provision "shell", path: "provision.sh"  
#   end

### centos ###
  config.vm.define "centos9" do |centos9|
    centos9.vm.box = "eurolinux-vagrant/centos-stream-9"
    centos9.vm.hostname = "centos9"
    centos9.vm.network "public_network", bridge: "enp2s0", ip: "192.168.1.111"
    centos9.vm.provider "virtualbox" do |vb|
      vb.cpus = 2
      vb.memory = "2048"
    end
    centos9.vm.provision "shell", path: "provision.sh"  
  end

#   config.vm.define "centos8" do |centos8|
#     centos8.vm.box = "centos/stream8"
#     centos8.vm.hostname = "centos8"
#     centos8.vm.network "public_network", bridge: "enp2s0", ip: "192.168.1.112"
#     centos8.vm.provider "virtualbox" do |vb|
#       vb.cpus = 2
#       vb.memory = "2048"
#     end
#     centos8.vm.provision "shell", path: "provision.sh"  
#   end

### arch ###
  config.vm.define "arch" do |arch|
    arch.vm.box = "generic/arch"
    arch.vm.hostname = "arch"
    arch.vm.network "public_network", bridge: "enp2s0", ip: "192.168.1.121"
    arch.vm.provider "virtualbox" do |vb|
      vb.cpus = 2
      vb.memory = "2048"
    end
    arch.vm.provision "shell", path: "provision.sh"  
  end

end
