Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true

### Jenkins VM ###
  config.vm.define "jenkins01" do |jenkins01|
    jenkins01.vm.box = "ubuntu/jammy64"
    jenkins01.vm.hostname = "jenkins01"
    jenkins01.vm.network "public_network", bridge: "enp0s25", ip: "172.16.172.91"
    jenkins01.vm.provider "virtualbox" do |vb|
      vb.cpus = 2
      vb.memory = "4096"
    end
    jenkins01.vm.provision "shell", path: "jenkins.sh"  
  end

### Nexus VM ###
  config.vm.define "nexus01" do |nexus01|
    nexus01.vm.box = "eurolinux-vagrant/centos-stream-9"
    nexus01.vm.hostname = "nexus01"
    nexus01.vm.network "public_network", bridge: "enp0s25", ip: "172.16.172.92"
    nexus01.vm.provider "virtualbox" do |vb|
      vb.cpus = 2
      vb.memory = "4096"
    end
    nexus01.vm.provision "shell", path: "nexus.sh"
  end

### Sonar VM ###
  config.vm.define "sonar01" do |sonar01|
    sonar01.vm.box = "ubuntu/jammy64"
    sonar01.vm.hostname = "sonar01"
    sonar01.vm.network "public_network", bridge: "enp0s25", ip: "172.16.172.93"
    sonar01.vm.provider "virtualbox" do |vb|
      vb.cpus = 2
      vb.memory = "4096"
    end
    sonar01.vm.provision "shell", path: "sonar.sh"  
  end

end
