Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true

  config.vm.provision "file", source: "~/.ssh/authorized_keys", destination: "/tmp/authorized_keys"

### Control VM ###
  config.vm.define "control01" do |control01|
    control01.vm.box = "ubuntu/jammy64"
    control01.vm.hostname = "control01"
    control01.vm.network "public_network", bridge: "enp0s25", ip: "172.16.172.90"
    control01.vm.provider "virtualbox" do |vb|
      vb.cpus = 2
      vb.memory = "4096"
    end
    control01.vm.provision "shell", path: "provision.sh"  
  end

### web VM ###
  config.vm.define "web01" do |web01|
    web01.vm.box = "eurolinux-vagrant/centos-stream-9"
    web01.vm.hostname = "web01"
    web01.vm.network "public_network", bridge: "enp0s25", ip: "172.16.172.91"
    web01.vm.provider "virtualbox" do |vb|
      vb.cpus = 2
      vb.memory = "4096"
    end
    web01.vm.provision "shell", path: "provision.sh"  
  end

  config.vm.define "web02" do |web02|
    web02.vm.box = "eurolinux-vagrant/centos-stream-9"
    web02.vm.hostname = "web02"
    web02.vm.network "public_network", bridge: "enp0s25", ip: "172.16.172.92"
    web02.vm.provider "virtualbox" do |vb|
      vb.cpus = 2
      vb.memory = "4096"
    end
    web02.vm.provision "shell", path: "provision.sh"  
  end

### db VM ###
  config.vm.define "db01" do |db01|
    db01.vm.box = "eurolinux-vagrant/centos-stream-9"
    db01.vm.hostname = "db01"
    db01.vm.network "public_network", bridge: "enp0s25", ip: "172.16.172.93"
    db01.vm.provider "virtualbox" do |vb|
      vb.cpus = 2
      vb.memory = "4096"
    end
    db01.vm.provision "shell", path: "provision.sh"  
  end

end
