Vagrant.configure("2") do |config|
  config.vm.synced_folder "../scripts", "/opt/scripts"

	config.vm.define "scriptbox" do |scriptbox|
		scriptbox.vm.box = "ubuntu/bionic64"
		scriptbox.vm.hostname = "scriptbox"
		scriptbox.vm.network "private_network", ip: "192.168.57.2"
    scriptbox.vm.network "public_network", bridge: "enp0s25", ip: "172.16.172.82"
		scriptbox.vm.provider "virtualbox" do |vb|
      vb.cpus = 2
			vb.memory = "2048"
	 	end
	end

	config.vm.define "web01" do |web01|
		web01.vm.box = "centos/7"
		web01.vm.hostname = "web01"
		web01.vm.network "private_network", ip: "192.168.57.3"
    web01.vm.network "public_network", bridge: "enp0s25", ip: "172.16.172.83"
		web01.vm.provider "virtualbox" do |vb|
      vb.cpus = 2
			vb.memory = "1024"
	 	end
	end

	config.vm.define "web02" do |web02|
		web02.vm.box = "centos/7"
		web02.vm.hostname = "web02"
		web02.vm.network "private_network", ip: "192.168.57.4"
    web02.vm.network "public_network", bridge: "enp0s25", ip: "172.16.172.84"
		web02.vm.provider "virtualbox" do |vb|
      vb.cpus = 2
			vb.memory = "1024"
	 	end
	end
end
