Vagrant.configure("2") do |config|
  config.vm.synced_folder "../scripts", "/opt/scripts"

	config.vm.define "scriptbox" do |scriptbox|
		scriptbox.vm.box = "geerlingguy/centos7"
		scriptbox.vm.hostname = "scriptbox"
		scriptbox.vm.network "private_network", ip: "192.168.56.12"
		scriptbox.vm.provider "virtualbox" do |vb|
      vb.cpus = 2
			vb.memory = "2048"
	 	end
    scriptbox.vm.network "public_network", bridge: "eno1", auto_config: false
    scriptbox.vm.provision "shell",
      run: "always",
      inline: "ifconfig enp0s9 172.16.5.72 netmask 255.255.254.0 up"
    scriptbox.vm.provision "shell",
      run: "always",
      inline: "route add default gw 172.16.5.254"
	end

	# config.vm.define "web01" do |web01|
	# 	web01.vm.box = "geerlingguy/centos7"
	# 	web01.vm.hostname = "web01"
	# 	web01.vm.network "private_network", ip: "192.168.56.13"
	# 	web01.vm.provider "virtualbox" do |vb|
  #     vb.cpus = 2
	# 		vb.memory = "2048"
	#  	end
	# end
	
	# config.vm.define "web02" do |web02|
	# 	web02.vm.box = "geerlingguy/centos7"
	# 	web02.vm.hostname = "web02"
	# 	web02.vm.network "private_network", ip: "192.168.56.14"
	# 	web02.vm.provider "virtualbox" do |vb|
  #     vb.cpus = 2
	# 		vb.memory = "2048"
	#  	end
	# end

	# config.vm.define "web03" do |web03|
	# 	web03.vm.box = "ubuntu/bionic64"
	# 	web03.vm.hostname = "web03"
	# 	web03.vm.network "private_network", ip: "192.168.56.15"
	# 	web03.vm.provider "virtualbox" do |vb|
  #     vb.cpus = 2
	# 		vb.memory = "2048"
	#  	end
	# end
end
