all:
  hosts:
    web01:
      ansible_host: 172.16.172.91
    web02:
      ansible_host: 172.16.172.92
    db01:
      ansible_host: 172.16.172.93

  children:
    webservers:
      hosts:
        web01:
        web02:
    dbservers:
      hosts:
        db01:
    servers:
      children:
        webservers:
        dbservers:
      vars:
        ansible_user: saibi
        ansible_ssh_private_key_file: clientkey.pem


